<?php
$product = array(
    "pudding_milk",
    "pudding_co",
    "pudding_mango",
    "pudding_sesame",
    "cheese_lemon",
    "cheese_strawberry",
    "cheese_coco",
    "cheese_greentea",
    "cheese_origin",
    "puffs",
    "luwei_claw",
    "luwei_wing",
    "luwei_smallwing",
    "luwei_gizzard",
    "luwei_drybean",
    "luwei_bubble",
    "luwei_combine",
    "luwei_duckwing",
    "mango",
    "malt_origin",
    "malt_blacksuger",
    "shrimp_salt",
    "shrimp_seaweed",
    "shrimp_pepper",
    "shrimp_hot"
);
$price = array(
    "pudding_milk" => 35,
    "pudding_co" => 35,
    "pudding_mango" => 35,
    "pudding_sesame" => 35,
    "cheese_lemon" => 65,
    "cheese_strawberry" => 65,
    "cheese_coco" => 65,
    "cheese_greentea"  => 65,
    "cheese_origin" => 65,
    "puffs"  => 250,
    "luwei_claw" => 40,
    "luwei_wing" => 40,
    "luwei_smallwing"  => 40,
    "luwei_gizzard" => 40,
    "luwei_drybean"  => 40,
    "luwei_bubble"  => 45,
    "luwei_duckwing" => 60,
    "luwei_combine"  => 220,   
    "mango" => 100,
    "malt_origin" => 120,
    "malt_blacksuger" => 120,
    "shrimp_salt" => 80,
    "shrimp_seaweed"=> 80,
    "shrimp_pepper"=> 80,
    "shrimp_hot"=> 80    
);
$name = array(
    "pudding_milk" => "伊蕾特布丁 - 鮮奶",
    "pudding_co" => "伊蕾特布丁 - 可可",
    "pudding_mango" => "伊蕾特布丁 - 芒果",
    "pudding_sesame" => "伊蕾特布丁- 芝麻",
    "cheese_lemon" => "伊蕾特乳酪塔 - 檸檬",
    "cheese_strawberry" => "伊蕾特乳酪塔 - 草莓",
    "cheese_coco" => "伊蕾特乳酪塔 - 經典可可",
    "cheese_greentea"  => "伊蕾特乳酪塔 - 抹茶紅豆",
    "cheese_origin" => "伊蕾特乳酪塔 - 雪藏原味",
    "puffs"  => "里夫蛋糕 - 手指泡芙",
    "luwei_claw" => "西井村滷味 - 雞爪",
    "luwei_wing" => "西井村滷味 - 雞翅",
    "luwei_smallwing"  => "西井村滷味 - 翅小腿",
    "luwei_gizzard" => "西井村滷味 - 雞胗",
    "luwei_drybean"  => "西井村滷味 - 豆干",
    "luwei_bubble"  => "西井村滷味 - 泡泡糖",
    "luwei_duckwing" => "西井村滷味 - 鴨翅",
    "luwei_combine"  => "西井村滷味 - 組合包",   
    "mango" => "玉井芒果乾",
    "malt_origin" => "章成麥芽餅 - 原味",
    "malt_blacksuger" => "章成麥芽餅 - 黑糖",
    "shrimp_salt" => "蝦到爆蝦餅 - 鹽味",
    "shrimp_seaweed"=> "蝦到爆蝦餅 - 海苔",
    "shrimp_pepper"=> "蝦到爆蝦餅 - 胡椒",
    "shrimp_hot"=> "蝦到爆蝦餅 - 辣味"    
);
?>